version: '2'
services:
  mysql:
    image: mariadb:latest
    restart: always
    container_name: tamerlinks_mysql
    volumes:
      # - ./database/source-db:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    env_file: .env
    ports:
      - "3361:3360"
  nginx:
    restart: always
    container_name: tamerlinks_nginx
    image: nginx:1.11.10
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/src
    depends_on:
      - api
      - client
    logging:
      options:
        max-size: '100k'
        max-file: '10'
  api:
    restart: always
    container_name: tamerlinks_api
    build:
      context: "."
    env_file: .env
    volumes:
      - .:/src
    logging:
      options:
        max-size: '100k'
        max-file: '10'
    depends_on:
      - redis
      - mysql
    links:
      - mysql:mysql
  client:
    restart: always
    container_name: tamerlinks_client
    image: node:10.6.0
    command: bash -c "cd client && npm install && export HOST=0.0.0.0 && npm run dev"
    volumes:
      - ./client:/client
    logging:
      options:
        max-size: '100k'
        max-file: '10'
  redis:
    image: "redis:alpine"
  celery:
      build: .
      container_name: tamerlinks_celery
      command: celery -A TamerLinks worker -l info
      volumes:
        - ./backend:/src
      depends_on:
        - api
      env_file: .env
  celery-beat:
      build: .
      container_name: tamerlinks_celerybeat
      command: celery -A TamerLinks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      volumes:
        - ./backend:/src
      depends_on:
        - celery
      env_file: .env
